#!/usr/bin/env zsh

if ! zgen saved; then
    zgen load 'docker/docker' contrib/completion/zsh
    zgen load 'docker/compose' contrib/completion/zsh
fi

alias d=docker
alias dc=docker-compose

alias d.purge.containers='docker ps -f status=exited -q | xargs docker rm --volumes'
alias d.rm.all.containers='docker ps -a -q | xargs docker rm --volumes -f'
alias d.purge.images='docker images -f dangling=true -q | xargs docker rmi'
alias d.purge.volumes='docker volume ls -f dangling=true -q | xargs docker volume rm'
alias d.purge.all='d.purge.containers && d.purge.volumes && d.purge.images'

