#!/usr/bin/env zsh

# for iTerm2 integration
bindkey '\ea' beginning-of-line
bindkey '\eA' end-of-line
bindkey '\es' backward-kill-word
bindkey '\eS' backward-kill-line
bindkey '\eu' undo

# completion options
#   'm:{a-zA-Z}={A-Za-z}' – case-insensitive
#   'r:|[._-]=* r:|=*' allows 'f.b' to expand to 'foo.bar'
#   'l:|=* r:|=*' allows 'bar' to expand to 'foobar'
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# automatically select the first suggestion
setopt menucomplete

setopt histverify


function {
    _sudo_or_accept_wrapped=$(zle -lL accept-line | cut -f 4 -d' ')
    eval "zle -N $_sudo_or_accept_wrapped"
    function _sudo_or_accept() {
        if [[ $BUFFER == '!!' ]]; then
            local last_line="$history[$[HISTCMD-1]]"
            zle kill-whole-line
            zle -U "sudo ${last_line}"
        else
            zle $_sudo_or_accept_wrapped
        fi
    }
    zle -N accept-line _sudo_or_accept
}
