#!/usr/bin/env zsh

include 'hooks'

# for iTerm2 integration
bindkey '\ea' beginning-of-line
bindkey '\eA' end-of-line
bindkey '\es' backward-kill-word
bindkey '\eS' backward-kill-line
bindkey '\eu' undo

# completion options
#   'm:{a-zA-Z}={A-Za-z}' – case-insensitive
#   'r:|[._-]=* r:|=*' allows 'f.b' to expand to 'foo.bar'
#   'l:|=* r:|=*' allows 'bar' to expand to 'foobar'
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# automatically select the first suggestion
setopt menucomplete

setopt histverify


hooks-define-hook zle_accept_line
function _run_hooks_or_default_accept() {
    hooks-run-hook zle_accept_line
    if [[ $? -ne 0 ]]; then
        return 0
    fi
    zle .accept-line
}
zle -N accept-line _run_hooks_or_default_accept


function _sudo_helper() {
    if [[ $BUFFER == '!!' ]]; then
        local last_line="$history[$[HISTCMD-1]]"
        zle kill-whole-line
        zle -U "sudo ${last_line}"
        return 1
    fi
}
hooks-add-hook zle_accept_line _sudo_helper

