#!/usr/bin/env zsh

if ! zgen saved; then
    zgen load zsh-users/zsh-completions src
fi

alias grep='grep -i'
alias ag='ag --smart-case --hidden'

alias o='open'

export EDITOR=mvim

pathToVimBinary=$(dirname $(which vim))/$(readlink $(which vim))
export vimless=$(dirname $pathToVimBinary)/../share/vim/vim80/macros/less.sh
alias vimless="$vimless"
alias L='vimless'
export MANPAGER="col -b | $vimless -c 'set ft=man nomod nolist' -"

alias p4merge='/Applications/p4merge.app/Contents/Resources/launchp4merge'
alias fix.open.with='/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain user;killall Finder;echo "Open With has been rebuilt, Finder will relaunch"'

export PERU_CACHE=$HOME/.cache/peru

alias time_="gtime -f '\ncompleted in %e seconds'"


# opens in new window on current space, even if another VimR windows exists on another space
function v () {
    osascript -e 'on run (argv)
        tell application "VimR" to openFilesInNewWindow (argv)
        activate application "VimR"
    end' "$(greadlink -f "$1")"
}

alias serve.this='mongoose -hide_files_patterns ".DS_Store"'

add_to_path $HOME/local/bin

source $HOME/.fzf.zsh
export FZF_DEFAULT_OPTS="--reverse --inline-info --no-sort"

# automatically update $PATH completion
zstyle ":completion:*:commands" rehash 1

alias nix-setup='. $HOME/.nix-profile/etc/profile.d/nix.sh'
alias nix=nix-env

