#!/usr/bin/env zsh

include editor
include keys
include memoize-init

function mkcd () { mkdir -p "$1" && cd "$1" }

setopt auto_cd
alias -- -='cd -'

if ! zgen saved; then
    zgen load Tarrasch/zsh-bd
fi
alias ...='bd 2'


memoize_init 'fasd --init zsh-hook posix-alias zsh-ccomp zsh-ccomp-install zsh-wcomp zsh-wcomp-install'

alias j=z
jj() {
    local dir
    dir="$(fasd -Rdl | fzf -1 -0 --no-sort +m -q "$1")" && cd "${dir}" || return 1
}

alias grt='cd $(git rev-parse --show-toplevel || echo ".")'

