#!/usr/bin/env zsh

if ! zgen saved; then
    # pure depends on async
    zgen load mafredri/zsh-async
    zgen load sindresorhus/pure
fi

# do not show the command execution time; there is no explicit way to disable it
PURE_CMD_MAX_EXEC_TIME=1000

