#!/usr/bin/env zsh

include zsh-async

rbenv_init="$ZGEN_DIR/init-rbenv.zsh"
if ! zgen saved; then
    echo Creating "$rbenv_init"
    rbenv init --no-rehash - zsh > "$rbenv_init"
fi
source "$rbenv_init"

async_start_worker rbenv
async_job rbenv rbenv rehash

