#!/usr/bin/env zsh

include zsh-async
include memoize-init

memoize_init 'rbenv init --no-rehash - zsh'

function {
    local worker=rbenv
    function dummy_callback() { }
    async_start_worker $worker
    async_register_callback $worker dummy_callback
    async_job $worker rbenv rehash
}
